services:
  client:
    build: ./client
    container_name: lesson-scheduler-client
    ports:
      - '80:80'
  api:
    build: ./api
    container_name: lesson-scheduler-server
    ports: 
      - '8080:8080'